# Generated by Django 4.1.7 on 2023-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0002_rename_product_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('article',)},
        ),
        migrations.AlterField(
            model_name='card',
            name='article',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
