# Generated by Django 4.1.7 on 2023-03-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0003_alter_card_options_alter_card_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='article',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
